from enum import Enum

class Respuesta(Enum):
    REQUERIR_NOMBRE_CURSO = 1
    INFORMACION_GENERAL_CURSO = 2
    INFORMACION_PROGRAMACION = 3
    SALUDO = 4
    AGRADECIMIENTO = 5
    INFORMACION_PAGO = 6
    INFORMACION_INCRIPCION = 7
    INFORMACION_COSTO_CURSO = 8
    INFORMACION_COSTO_PROGRAMA = 9